---
version: 0
os: linux
files:
  - source: /main
    destination: /home/linux/<spring>
permissions:
  - object: /home/linux/<spring>
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu
