version: 0.2

phases:
  install:
    runtime-versions:
      java: Corretto-17
  build:
    commands:
      - ./gradlew build --scan
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - demo-app1.jar
    base-directory: 'build/libs'
  discard-paths: yes
